### ISSUE TITLE
`navigator.maxTouchPoints` is not part of Touch Events

### ISSUE THREAD

**Issue by patrickhlauke** [rafrex/detect-touch-events#2]
Possibly something to clarify in the README: `navigator.maxTouchPoints` has nothing to do with the Touch Events spec. It is defined in the Pointer Events spec https://w3c.github.io/pointerevents/#dom-navigator-maxtouchpoints

Of course, this muddies the issue a bit since the name of this whole repo suggests it's about TE. perhaps the name should be generalised to just `detect-touch-capability` or similar?

**Comment by rafgraph** [comment]
@patrickhlauke I had included `maxTouchPoints` because Chrome on Android had supported it before it supported Pointer Events (you know, the messy real world). I actually haven't had a need to use `maxTouchPoints` so I removed it from v2.
