### ISSUE TITLE
maxTouchPoints returns undefined if TE check fails

### ISSUE THREAD

**Issue by patrickhlauke** [rafrex/detect-touch-events#3]
Related to https://github.com/rafrex/detect-touch-events/issues/2 - currently, `maxTouchPoints` returns undefined if the legacy TE detect returns false. However, `navigator.maxTouchPoints` can indeed be defined (and even have value > 0) when no TE support is present, since it's part of the Pointer Events spec. (case in point: see https://patrickhlauke.github.io/touch/tests/pointer-multitouch-detect.html in a recent stable Chrome build)

**Comment by rafgraph** [comment]
@patrickhlauke this was intentional so as to not confuse developers back when Chrome on Android supported `maxTouchPoints` but not Pointer Events, but is moot as I removed `maxTouchPoints` from v2.
