### ISSUE TITLE
Getting window is not defined error

### ISSUE THREAD

**Issue by praneetaj** [rafrex/detect-touch-events#5]
ReferenceError: window is not defined
    `at Object.update (/Users/praneetaj/stash/FE/home-details-components/node_modules/detect-touch-events/lib/index.js:8:9)`

It should check for
 `typeof window !== 'undefined'`
instead

**Comment by rafgraph** [comment]
Hi, thanks! Sorry for the late reply, was on vacation.

The PR has been merged and new versions published on npm:
`detect-touch-events` v2.0.1
[`detect-it`](https://github.com/rafrex/detect-it) v3.0.2
